apiVersion: v1
kind: Service
metadata:
  name: mssql-exporter-official
  labels:
    exporter: mssql
spec:
  selector:
    app: mssql-exporter-official
  ports:
    - name: metrics
      protocol: TCP
      port: 4000
      targetPort: 4000
