apiVersion: v1
kind: Service
metadata:
  name: mssql-exporter-querier
  labels:
    exporter: mssql
spec:
  selector:
    app: mssql-exporter-querier
  ports:
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
