{
 "title": "Prometheus MSSQL Exporter PoC",
 "description": "Performance and health metrics for Prometheus MSSQL Exporter running on docker.",
 "tags": [
  "prometheus",
  "SQL Server"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "up" },
   {
    "name": "database_name",
    "query": "mssql_connections{mssql=\"$stage\"}"
   },
   {
    "name": "stage",
    "label": "stage",
    "query": "up{job=\"$job\"}"
   }
  ]
 },
 "panels": [
  { "title": "General Instance properties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DATABASE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{mssql=\"$stage\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "State OFFLINE",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Total Deadlocks since last restart",
   "type": "singlestat",
   "description": "Number of lock requests per second that resulted in a deadlock since last restart:\n `SELECT cntr_value\nFROM sys.dm_os_performance_counters\nwhere counter_name = 'Number of Deadlocks/sec' AND instance_name = '_Total'`",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_deadlocks{mssql=\"$stage\"}",
     "measurement": "State ONLINE",
     "query": "SELECT \"total\" FROM \"State ONLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Kill Connection Errors since last restart",
   "type": "singlestat",
   "description": "Number of kill connection errors/sec since last restart\n`SELECT cntr_value\nFROM sys.dm_os_performance_counters\nwhere counter_name = 'Errors/sec' AND instance_name = 'Kill Connection Errors'`",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_kill_connection_errors{mssql=\"$stage\"}",
     "measurement": "State OFFLINE",
     "query": "SELECT \"total\" FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Current Number of Transact-SQL/sec",
   "type": "singlestat",
   "description": "Number of Transact-SQL command batches received per second. This statistic is affected by all constraints (such as I/O, number of users, cachesize, complexity of requests, and so on). High batch requests mean good throughput\n`SELECT rtrim(instance_name),cntr_value\nFROM sys.dm_os_performance_counters where counter_name = 'Log Growths'\nand  instance_name <> '_Total'`",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(mssql_batch_requests{mssql=\"$stage\"}[5m])",
     "measurement": "State RECOVERING",
     "query": "SELECT \"total\" FROM \"State RECOVERING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Number of page faults/sec",
   "type": "singlestat",
   "description": "Number of page faults per second `SELECT page_fault_count, memory_utilization_percentage \nfrom sys.dm_os_process_memory`",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(mssql_page_fault_count{mssql=\"$stage\"}[5m])",
     "legendFormat": "Page Fault Count",
     "measurement": "State RECOVERY_PENDING",
     "query": "SELECT \"total\" FROM \"State RECOVERY_PENDING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Number of Transact-SQL/sec",
   "type": "graph",
   "description": "Number of Transact-SQL command batches received per second. This statistic is affected by all constraints (such as I/O, number of users, cachesize, complexity of requests, and so on). High batch requests mean good throughput\n`SELECT rtrim(instance_name),cntr_value\nFROM sys.dm_os_performance_counters where counter_name = 'Log Growths'\nand  instance_name <> '_Total'`",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_batch_requests{mssql=\"$stage\"}[5m])",
     "legendFormat": "transactions"
    }
   ]
  },
  { "title": "Instance Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory used",
   "type": "gauge",
   "description": "Percentage of memory utilization\n`SELECT total_physical_memory_kb, available_physical_memory_kb, available_page_file_kb \nfrom sys.dm_os_sys_memory`",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "(mssql_total_physical_memory_kb{mssql=\"$stage\"} - mssql_available_physical_memory_kb{mssql=\"$stage\"}) / mssql_total_physical_memory_kb{mssql=\"$stage\"} * 100 ",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "SQL process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "singlestat",
   "description": "Total physical memory\n`SELECT total_physical_memory_kb \nfrom sys.dm_os_sys_memory`",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 12 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_total_physical_memory_kb{mssql=\"$stage\"} / 1024",
     "measurement": "Performance metrics",
     "query": "SELECT \"Point In Time Recovery\" FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter",
     "select": [
      [
       { "params": [ "Point In Time Recovery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "description": "Available physical memory `SELECT available_physical_memory_kb\nfrom sys.dm_os_sys_memory`",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 12 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_available_physical_memory_kb{mssql=\"$stage\"} / 1024",
     "measurement": "Recovery Model FULL",
     "query": "SELECT \"total\" FROM \"Recovery Model FULL\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Total Page File",
   "type": "singlestat",
   "description": "Total page file in KB\n`SELECT total_page_file_kb\nfrom sys.dm_os_sys_memory`",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 12 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_total_page_file_kb{mssql=\"$stage\"} / 1024",
     "measurement": "Recovery Model BULK_LOGGED",
     "query": "SELECT \"total\" FROM \"Recovery Model BULK_LOGGED\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Available Page File",
   "type": "singlestat",
   "description": "Available page file\n`SELECT available_page_file_kb \nfrom sys.dm_os_sys_memory`",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 12 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mssql_available_page_file_kb{mssql=\"$stage\"} / 1024",
     "measurement": "Recovery Model SIMPLE",
     "query": "SELECT \"total\" FROM \"Recovery Model SIMPLE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  { "title": "Database Properties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Active Connections",
   "type": "graph",
   "description": "Number of active connections `SELECT DB_NAME(sP.dbid)\n        , COUNT(sP.spid)\nFROM sys.sysprocesses sP\nGROUP BY DB_NAME(sP.dbid)`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_connections{mssql=\"$stage\",database=\"$database_name\",state=\"current\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active Connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of user errors/sec",
   "type": "graph",
   "description": "Number of user errors/sec\n`SELECT cntr_value\nFROM sys.dm_os_performance_counters\nwhere counter_name = 'Errors/sec' AND instance_name = 'User Errors'`",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_user_errors{mssql=\"$stage\"}[5m])",
     "legendFormat": "User errors"
    }
   ]
  },
  {
   "title": "Write Wait Stall Time (s)",
   "type": "graph",
   "description": "Write Wait Stall Time (s)\n`SELECT\ncast(DB_Name(a.database_id) as varchar) as name,\n    max(io_stall_read_ms),\n    max(io_stall_write_ms),\n    max(io_stall),\n    max(io_stall_queued_read_ms),\n    max(io_stall_queued_write_ms)\nFROM\nsys.dm_io_virtual_file_stats(null, null) a\nINNER JOIN sys.master_files b ON a.database_id = b.database_id and a.file_id = b.file_id\ngroup by a.database_id`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s", "label": "Stall time" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_io_stall{mssql=\"$stage\", database=\"$database_name\",type=\"write\"}[5m]) / 1000",
     "legendFormat": "Write Stall Time"
    }
   ]
  },
  {
   "title": "Read Wait Stall Time (s)",
   "type": "graph",
   "description": "Read Wait time (s) of stall\n`SELECT\ncast(DB_Name(a.database_id) as varchar) as name,\n    max(io_stall_read_ms),\n    max(io_stall_write_ms),\n    max(io_stall),\n    max(io_stall_queued_read_ms),\n    max(io_stall_queued_write_ms)\nFROM\nsys.dm_io_virtual_file_stats(null, null) a\nINNER JOIN sys.master_files b ON a.database_id = b.database_id and a.file_id = b.file_id\ngroup by a.database_id`",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s", "label": "Stall time" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_io_stall{mssql=\"$stage\", database=\"$database_name\",type=\"read\"}[5m]) / 1000",
     "legendFormat": "Read Stall Time"
    }
   ]
  },
  {
   "title": "Write Queue Stall Time (ms) ",
   "type": "graph",
   "description": "Write Queue Stall Time (ms)  `SELECT\ncast(DB_Name(a.database_id) as varchar) as name,\n    max(io_stall_read_ms),\n    max(io_stall_write_ms),\n    max(io_stall),\n    max(io_stall_queued_read_ms),\n    max(io_stall_queued_write_ms)\nFROM\nsys.dm_io_virtual_file_stats(null, null) a\nINNER JOIN sys.master_files b ON a.database_id = b.database_id and a.file_id = b.file_id\ngroup by a.database_id`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms", "label": "Stall time" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_io_stall{mssql=\"$stage\", database=\"$database_name\",type=\"queued_write\"}[5m])",
     "legendFormat": "Queued Write Stall Time"
    }
   ]
  },
  {
   "title": "Read Queue Stall Time (ms)",
   "type": "graph",
   "description": "Read Queue Stall Time (ms) `SELECT\ncast(DB_Name(a.database_id) as varchar) as name,\n    max(io_stall_read_ms),\n    max(io_stall_write_ms),\n    max(io_stall),\n    max(io_stall_queued_read_ms),\n    max(io_stall_queued_write_ms)\nFROM\nsys.dm_io_virtual_file_stats(null, null) a\nINNER JOIN sys.master_files b ON a.database_id = b.database_id and a.file_id = b.file_id\ngroup by a.database_id`",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms", "label": "Stall time" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_io_stall{mssql=\"$stage\", database=\"$database_name\",type=\"queued_read\"}[5m])",
     "legendFormat": "Queued Read Stall Time"
    }
   ]
  },
  {
   "title": "SQL Re-Compilations/sec",
   "type": "graph",
   "description": "Number of statement recompiles per second. Counts the number of times statement recompiles are triggered. Generally, you want the recompiles to be low\n`SELECT cntr_value\nFROM sys.dm_os_performance_counters\nwhere counter_name = 'SQL Re-Compilations/sec'`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_sql_recompilations{mssql=\"$stage\"}[5m])"
    }
   ]
  },
  {
   "title": "SQL Compilations/sec",
   "type": "graph",
   "description": "Number of SQL compilations per second. Indicates the number of times the compile code path is entered. Includes compiles caused by statement-level recompilations in SQL Server. After SQL Server user activity is stable, this value reaches a steady state\n `SELECT cntr_value\nFROM sys.dm_os_performance_counters\nwhere counter_name = 'SQL Compilations/sec'`",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_sql_compilations{mssql=\"$stage\"}[5m])",
     "legendFormat": "Queued Write Stall Time"
    }
   ]
  },
  {
   "title": "Buffer cache hit ratio",
   "type": "graph",
   "description": "Indicates the percentage of pages found in the buffer cache without having to read from disk. The ratio is the total number of cache hits divided by the total number of cache lookups over the last few thousand page accesses. After a long period of time, the ratio moves very little\n`SELECT cntr_value\nFROM sys.dm_os_performance_counters\nwhere counter_name = 'Buffer cache hit ratio'`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_buffer_cache_hit_ratio{mssql=\"$stage\"}",
     "legendFormat": "Queued Write Stall Time"
    }
   ]
  },
  {
   "title": "Checkpoint pages/sec",
   "type": "graph",
   "description": "Indicates the number of pages flushed to disk per second by a checkpoint or other operation that require all dirty pages to be flushed\n `SELECT cntr_value\nFROM sys.dm_os_performance_counters\nwhere counter_name = 'Checkpoint pages/sec'`",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mssql_checkpoint_pages{mssql=\"$stage\"}[5m])",
     "legendFormat": "Queued Write Stall Time"
    }
   ]
  },
  {
   "title": "Number of lock requests per second that required the caller to wait/sec",
   "type": "graph",
   "description": "Number of lock requests per second that required the caller to wait\n`SELECT cntr_value\nFROM sys.dm_os_performance_counters\nwhere counter_name = 'Lock waits/sec' and instance_name = '_Total'`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_lock_waits{mssql=\"$stage\"}[5m])",
     "legendFormat": "Queued Write Stall Time"
    }
   ]
  },
  {
   "title": "Page Splits/sec",
   "type": "graph",
   "description": "Number of page splits per second that occur as the result of overflowing index pages\n`SELECT cntr_value\nFROM sys.dm_os_performance_counters\nwhere counter_name = 'Page Splits/sec'`",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mssql_page_splits{mssql=\"$stage\"}[5m])",
     "legendFormat": "Queued Write Stall Time"
    }
   ]
  }
 ]
}