apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator
  name: mssql-exporter
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      exporter: mssql
